name: movabletype/mt-block-editor-example-plugins
on: [push]
jobs:
  build:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y zip

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Archive example plugins
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: |
            dist

  release:
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Download example plugins
        uses: actions/download-artifact@v4
        with:
          name: examples
          path: dist

      - name: Upload package to GitHub Releases
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          draft: true
          files: |
            dist/*.zip
