name: movabletype/mt-rich-text-editor-example-plugins
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install libs
        run: sudo apt-get install --no-install-recommends -y zip

      - name: Build plugin
        run: npm run build

      - name: Archive example plugins
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: |
            dist
